### ISSUE TITLE
[ERROR] Failing HTTP status code on MacOS

### ISSUE THREAD

**Issue by boomam** [ElliotKillick/Mido#8]
Hi,
Great script, potentially very useful - but I've not got it working yet...

Steps -  
I created local working folder, wget'd the .sh, chmod, etc. then ran - 
`./Mido.sh win11x64`

Error produced each time i attempt - 
```
[!] Microsoft servers returned failing HTTP status code!

[!] 1 attempted download(s) failed! Please re-run Mido with these arguments to try downloading again (any partial downloads will be resumed): win11x64
```

I can duplicate this across multiple networks, so i'm not sure its a network issue per-say.

Has this error been seen before?

Thanks!

**Comment by ElliotKillick** [comment]
I cannot reproduce. Make sure you're not living in a restricted region. Please try with Fido. If you don't get the issue on Fido then it must be an issue in Mido: https://github.com/pbatard/Fido

**Comment by boomam** [comment]
Bit premature to close the issue ...

Fido works fine.
What steps can we diagnose with mido?

**Comment by ElliotKillick** [comment]
It's difficult to say what the issue is given that I can't reproduce the bug. It works on my home network and from a VPS both located in Canada. Can you please give me the log output of this command: `DEBUG=1 ./Mido.sh win11x64`

Testing on Linux may be worth a shot.

**Comment by boomam** [comment]
Morning,
On MacOS - 
Tested with DEBUG=1 and the only error displayed is the same error posted above, and `+ media_download_failed_argument_list= win11x64`.  
Everything else is successful, including checksums.
Tested with win10x64, same error.

On Linux/Debian - 
Script doesn't run at all, instead spitting out the entire file on one line, starting with `./Mido.sh: line 1: syntax error near unexpected token `('`

**Comment by ElliotKillick** [comment]
I don't own a Mac so I've never been able to test on one. It would have been good to mention you're on Mac in the initial issue. Please throw up the full log on Pastebin so I can easily diff it with a Linux log to diagnose the issue.

What Mac version are you are on specifically? I suspect you may not may not have the `uuidgen` program (or that it functions differently from on Linux).

**Comment by boomam** [comment]
Hi,
Mentioned it in the issue title ;-)

You can close the issue, I decided to just get the iso's, when needed, a different way.

Thanks.

**Comment by ElliotKillick** [comment]
Sorry @boomam, I believe I updated the title just now? Unless I'm missing something, in which case please let me know. I'm glad you found a solution that works for you! :)

**Comment by boomam** [comment]
Ha, so you did. 😆
I only scrolled up to double check wording, didn't check the issue timeline in detail, it was a few months ago. 

Regardless, bash is bash, shell is shell.
If the current theory is that there are prerequisites for certain OS's/versions, then let's maybe get the readme updated to take this into account. 

To be clear, I don't need this solving, but happy to test the theory when I get a moment, and submit a PR if it is that missing package/library as the solution.

**Comment by ElliotKillick** [comment]
Yeah, `uuidgen` is one exception to the pure POSIX rule because UUIDs weren't really around when POSIX was being made. So, the program just hasn't been added to the standard yet. Same thing with the `sha256sum` command (for which we cannot feasibly implement a pure shell substitute).

I've considered adding a UUID generator using pure shell to the script but all the examples I've seen are a lot of code and also they may lack randomness compared to `uuidgen`. Both of these programs are common across Unix-like OSs though.

If you have a moment then please test `uuidgen --random`, it would be appreciated.
