### ISSUE TITLE
Updated Win11 23H2 SHA-256

### ISSUE THREAD

**Issue by Darkhand81** [ElliotKillick/Mido#9]
Hello! 

Absolutely love this tool, just discovered it when researching the absurdity that is MS's iso download process and it's already saved me a ton of sanity.

Thought I'd submit the current SHA-256 for WIn11 23H2:

71a7ae6974866603d366a911b0c00eace476e0b49d12205d7529765cc50b4b39

Verified via my own downloads using Mido and: https://answers.microsoft.com/en-us/windows/forum/all/windows-11-23h2-multi-edition-iso-is-released-by/6aae0a33-fb9c-4e26-be2e-2fdeeb53b268

Thanks again for this!

**Comment by ElliotKillick** [comment]
Thanks! I've updated the checksum.
